### ISSUE TITLE
Add an option to use Huggingface metrics

### ISSUE THREAD

**Issue by yuvalkirstain** [PyTorchLightning/lightning-transformers#206]
## 🚀 Feature

Support Huggingface metrics.

### Motivation

Torchmetrics are great, but there are many metrics that are not publicly available. Luckily, Huggingface implemented lots of them. Can you please an easy way to add metrics from Huggingface?

### Pitch

Specifying a metric from Huggingface, making sure I give it the correct arguments without needing to implement it on my own.

**Comment by mathemusician** [comment]
@yuvalkirstain I think this is a great idea! But after adding a metric to torchmetrics ([link](https://github.com/PyTorchLightning/metrics/pull/668)), I'll be the first to say that this might be a little tricky. There's a lot refactoring going on.

**Comment by mathemusician** [comment]
How did we want to swap metrics? I'm imagining that in the yaml, it looks like:

```yaml
metrics:
  accuracy:
    path: torchmetrics.Accuracy
  recall:
    path: torchmetrics.Recall
```

And we can swap it by switching it to:

```yaml
metrics:
  accuracy:
    path: datasets.metrics.Accuracy
  recall:
    path: datasets.metrics.Recall
```

If there's a custom metric, we can format it like:

```yaml
metrics:
  MyCustomMetric:
    path: abs/path/to/metric.py
```

Where it tries to import MyCustomMetrics from `abs/path/to/metric.py`

Also, with a few metrics, the targets/preds order are switched or are in the process of being switched. So it might be good to generalize metric as a dataclass, just like what HuggingFace is doing, where the output is a callable dictionary. All thoughts on this are welcome!
